# CI Link checker configuration
# See https://github.com/lycheeverse/lychee/blob/master/lychee.example.toml

# Exclude URLs and mail addresses from checking (supports regex).
# Please explain the inclusion of each one.
exclude = [
    # These will always be 404s unless you're authed
    "https://github.com/satisfactorymodding/UnrealEngine/",
    "https://github.com/EpicGames/UnrealEngine/",
    "https://github.com/EpicGames-Mirror-A/UnrealEngine/",
    "https://github.com/SatisfactoryModdingUE/UnrealEngine/",
    # Site seems to disallow robots
    "https://cable.ayra.ch/satisfactory/editor.php",
    # Reports a 404 despite the link working?
    "https://www.unrealengine.com/en-US/blog/download-our-new-blender-addons",
    # Possible not allowing robots, receiving 403
    "https://steamdb.info/app/526870/",
    # Don't check edit links for the docs itself (randomly 403s but also why check these anyways)
    "https://github.com/satisfactorymodding/Documentation/edit/",
    # Don't check license links at the bottom of pages, seems to frequently "Failed: Network error: unexpected EOF"
    "https://www.gnu.org/",
    # This is a valid page but still 404s for some reason
    "https://www.audiokinetic.com/en/download/",
    # unable to get local issuer certificate
    "https://questions.satisfactorygame.com/",
    # 403s despite being valid pages
    "https://stackoverflow.com/questions/",
    "https://www.unrealengine.com/en-US/ue-on-github",
    "https://store.epicgames.com/en-US/p/satisfactory",
    # 403s despite being valid page, we should try to get this working somehow, since these links can change without warning
    "https://docs.unrealengine.com/",
    "https://dev.epicgames.com/",
    # Times out despite being valid
    "https://www.adobe.com/learn/substance-3d-designer/web/the-pbr-guide-part-1"
]

# Exclude these filesystem paths from getting checked.
# TODO find a better way to handle sub-mods, as they currently must be ignored here
# else they'll fail the the whole build if they have broken links.
exclude_path = [
    "./build/site/ficsit-networks/",
    "./build/site/ficsitremotemonitoring/"
]
